apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Values.ipAddressPool.namespace }}
spec:
  addresses:
  {{- range .Values.ipAddressPool.addresses }}
  - {{ . }}
  {{- end }}
  autoAssign: {{ .Values.ipAddressPool.autoAssign }}

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: {{ .Values.l2Advertisement.namespace }}
  name: {{ .Values.l2Advertisement.name }}
spec:
  ipAddressPools:
  {{- range .Values.l2Advertisement.ipAddressPools }}
  - {{ . }}
  {{- end }}
  interfaces: 
  {{- range .Values.l2Advertisement.interfaces }}
  - {{ . }}
  {{- end }}
