# Ingress Nginx 설정
ingress-nginx:
  enabled: true
  controller:
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
      controllerValue: "k8s.io/ingress-nginx"
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nlb"
        service.beta.kubernetes.io/ncloud-load-balancer-internal: "false"
        #service.beta.kubernetes.io/ncloud-load-balancer-subnet-id: "452772"  #서브넷을 지정해야 하는 경우 사용
    replicaCount: 2
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
    resources:
      limits:
        cpu: 300m
        memory: 128Mi
      requests:
        cpu: 300m
        memory: 128Mi

  # 네임스페이스 설정
  namespaceOverride: "ingress-nginx"
