prometheus:
  enabled: true
  global:
    scrape_interval: 1m
    evaluation_interval: 1m

  server:
    retention: 15d
    retentionSize: 90GB
    persistentVolume:
      size: 100Gi
      storageClass: nfs-client
  
  alertmanager:
    enabled: false