apiVersion: v2
name: nfs-k8s
description: A Helm chart for NFS (DEV)
type: application
version: 1.0.0
appVersion: "4.0.18"


dependencies:
  - name: nfs-subdir-external-provisioner
    version: 4.0.18
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    condition: nfs-subdir-external-provisioner.enabled
