# 컴포넌트 활성화 설정
env: stg
project: poc-k8s
namespaceOverride: "stg-nfs-subdir"
createNamespace: true 
nfs-subdir-external-provisioner:
  enabled: true
  nfs:
    server: nfs-poc.example.co.kr
    path: /DATA/poc-stg-k8s
  storageClass:
    name: nfs-client
    pathPattern: "${.PVC.name}"
    provisionerName: cluster.local/nfs-subdir-external-provisioner
    archiveOnDelete: false
    onDelete: retain
    reclaimPolicy: Retain

       