apiVersion: v2
name: prd-nfs-subdir
description: A Helm chart for Kubernetes Cluster (PRD)
type: application
version: 4.0.18
appVersion: "4.0.2"


dependencies:
  - name: nfs-subdir-external-provisioner
    version: 4.0.18
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    condition: nfs-subdir-external-provisioner.enabled
